export const images = {
  edit: require('../assests/images/edit.png'),
  camera: require('../assests/images/ic_camera.png'),
  profile: require('../assests/images/profile.png'),
  cover: require('../assests/images/Cover.png'),
  rightArrow: require('../assests/images/rightarrow.png'),
  calendar: require('../assests/images/ic_calendar.png'),
  rightcheck: require('../assests/images/ic_check.png'),
  checkbox: require('../assests/images/ic_checkmark_big.png'),
  correct: require('../assests/images/correct.png'),
  google: require('../assests/images/google_logo.png'),
  apple: require('../assests/images/apple_logo.png'),
  backarrow: require('../assests/images/backarrow.png'),
  bmx: require('../assests/images/BMX1.png'),
  rectangle: require('../assests/images/Rectangle6.png'),
  footerPattern: require('../assests/images/footerPattern.png'),
  like: require('../assests/images/thumb.png'),
  dialogBox: require('../assests/images/Dialog_Box.png'),
  fan: require('../assests/images/fan.png'),
  athlete: require('../assests/images/athl.png'),
  cancel: require('../assests/images/ic_cancel.png'),
  eyeClosed: require('../assests/images/closedEye.png'),
  eyeOpen: require('../assests/images/openEye.png'),
  check: require('../assests/images/check.png'),
  star:require('../assests/images/starImg.png'),
  splashMan:require('../assests/images/splashManImg.png'),
  five:require('../assests/images/Union.png'),
  backgroundSplash:require('../assests/images/backgroundSplashImg.png'),
  searchImg:require('../assests/images/searchImg.png')
};
