export const STRINGS = {
  LABEL: {
    TERMS: 'Terms of Use',
    SUBMIT: 'SUBMIT',
    VERIFICATION: 'Enter Verification Code',
    EDIT: 'Edit',
    TAG_LINE_VERIFICATION:'Kindly enter the 4 digit verification code sent to ',
    CONTINUE: 'CONTINUE',
    ACCOUNT_SUCCESSFULLY: 'Your account has been successfully ',
    REGISTERTED: 'registered',
    CONGRATULATIONS: 'CONGRATULATIONS',
    ATHLETE: 'ATHLETE',
    FAN: 'FAN',
    SELECT_IDENTITY: 'Select your identity',
    CREATE_ACCOUNT: 'Create Account',
    SIGN_IN: 'SIGN IN',
    FULL_NAME: 'Full Name*',
    SIGN_UP_TAGLINE: 'Sign-up to get started',
    MOBILE_NUMBER: 'Mobile Number*',
    EMAIL: 'Email*',
    PASSWORD: 'Password*',
    AGREE_TO: 'I agree to',
    TERMS_TEXT: 'Terms of Use*',
    OR: ' OR ',
    ALREADY_USER: 'Already a user',
    NUMBER_PAD: 'number-pad',
    RESEND_VERIFY_CODE: 'Resend Verification Code',
    DID_NOT_RECEIVE_CODE: "Didn't received the code yet?",
    ENTER_4_DIGIT_VERIFY_CODE:'Kindly enter the 4 digit verification code sent to ',
    USER_NUMBER: '+17345678926',
    CHANGE_YOUR_USERNAME: 'Change your Username',
    DOB: 'Date of Birth',
    ZIPCODE: 'Zipcode',
    BIO: 'Bio',
    SEARCH:'Search',
    REFERRAL_CODE: 'Referral Code',
    SPORT_WATCH: 'Sport I Watch',
    USER_TELL_US_HEADER: 'Hi John! \nTell us about yourself',
    NEXT: 'NEXT',
    SELECT_IDENTITY_SCREEN:"selectIdentity",
    MOBILE_NO_OR_EMAIL : "Mobile Number/ Email",
    FORGET_PASSWORD: "Forget Password?",
    SIGN_IN_HEADER: "Sign In Using Your Mobile Number/Email",
    I_AM_NEW_USER: "I'm a new user ",
    SIGN_UP:"Sign Up",
    SIGN__IN:"Sign In",
    SEARCH_SPORTS:"Search Sports",
    WHICH_SPORTS_PLAY:"What sport do you like to Play?",
    SPLASH:"splash",
    SELECT_COUNTRY:"Select a Country",
    SEARCH_COUNTRY:"Search Country",
    WHO_ARE_YOU:"Who are you?",
    ADD_NEW:"+ Add New",
    _FAN:"Fan",
    _ATHL:"Athlete",
    SUGGESTION:"Suggestions:"
  },
  TermsofUse: {
    Terms1:
      'The Fivestar Mobile Application (“App”) and all services provided through the App (collectively, “Services”) are made available by Fivestar App, Inc. (“Fivestar,” “us,” “our,” and/or “we”).  Certain features of the App and Services may be subject to additional guidelines, terms, or rules, which will be posted through the App or Services in connection with such features.  All such additional terms, guidelines, and rules are incorporated by reference into this Agreement.  References to “you” and “your” refer to you, a user of our App and/or Services.',
    Terms2:
      'THESE TERMS OF USE (“AGREEMENT”) SET FORTH THE LEGALLY BINDING TERMS FOR YOUR USE OF THE APP AND SERVICES.  BY ACCESSING OR USING THE APP OR SERVICES, YOU ARE ACCEPTING THIS AGREEMENT AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THIS AGREEMENT.  YOU MAY NOT ACCESS OR USE THE APP OR SERVICES OR ACCEPT THE AGREEMENT IF YOU DO NOT HAVE THE CAPACITY TO ENTER INTO THIS AGREEMENT.  IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THIS AGREEMENT, DO NOT ACCESS AND/OR USE THE APP OR SERVICES.  IF YOU ARE USING THE APP OR SERVICES ON BEHALF OF A COMPANY, ENTITY, OR ORGANIZATION, YOU REPRESENT AND WARRANT THAT YOU ARE AN AUTHORIZED REPRESENTATIVE OF SUCH COMPANY, ENTITY, OR ORGANIZATION WITH THE AUTHORITY TO BIND IT TO THIS AGREEMENT.',
  },
  SCREEN: {
    SIGN_UP_PROFILE: 'SignupProfile',
    EDIT_UP_PROFILE: 'EditProfile',
    OTP_VERIFY: 'OtpVerify',
    TERMS_SCREEN: 'TermsScreen',
    SIGN_IN_SCREEN : "SignInScreen",
    SPORT:"SportScreen",
    ZIPCODE:"zipCodeScreen"
  },
  ERROR_MSG: {
    NAME: {
      MUST_HAVE: 'Please Enter a valid name',
      MIN_3_CHARACTER: 'Name should be min of 3 characters',
      EMPTY: '',
    },
    ALREADY_USER:'Username alreadty exits. Please try using another username'
  },
};
