import {StyleSheet} from 'react-native';
import {normalize} from '../../utils/dimensions';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: 'black',
  },
  imgContainer: {
    height: normalize(310),
    width: normalize(368),
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'center',
  },
  imgCover: {
    width: normalize(358),
    height: normalize(218),
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    bottom: normalize(20),
    resizeMode: 'contain',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgProfile: {
    width: normalize(101),
    height: normalize(101),
    borderWidth: 1,
    borderColor: 'white',
    bottom: normalize(10),
    borderRadius: 5,
  },
  imgProfileSelected: {
    width: normalize(100),
    height: normalize(100),
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 5,
  },
  header: {
    fontSize: 28,
    fontWeight: '900',
    color: 'white',
    marginLeft: normalize(15),
    marginTop: normalize(40),
    fontStyle: 'italic',
  },
  edit: {
    height: normalize(45),
    width: normalize(30),
    justifyContent: 'center',
    position: 'absolute',
    right: normalize(10),
    top: normalize(10),
  },
  editImageStyle: {
    height: normalize(20),
    width: normalize(18),
    resizeMode: 'contain',
  },
  RightArrowImageStyle: {
    height: normalize(20),
    width: normalize(20),
    resizeMode: 'contain',
  },
  calendarImageStyle: {
    height: normalize(18),
    width: normalize(20),
    resizeMode: 'contain',
  },
  submitText: {
    fontSize: 30,
    fontWeight: '400',
    backgroundColor: 'black',
  },
  body: {
    borderRadius: 1,
    borderWidth: 1,
  },
  cameraImg: {
    height: normalize(26),
    position: 'absolute',
    width: normalize(26),
    resizeMode: 'contain',
    alignSelf: 'center',
    opacity: 0.6,
  },
  profileCameraImg: {
    height: normalize(22),
    width: normalize(22),
    position: 'absolute',
    alignSelf: 'center',
    marginTop: normalize(39),
    right: normalize(37),
    opacity: 0.6,
  },
  selectView: {
    borderWidth: 1,
    borderRadius: 6,
    borderColor: 'white',
    marginTop: normalize(10),
    flexDirection: 'row',
    height: normalize(48),
    marginBottom: normalize(20),
    justifyContent: 'space-between',
    paddingHorizontal: normalize(18),
    alignItems: 'center',
    paddingVertical: normalize(10),
  },
  selectIdentityText: {
    color: 'white',
    fontSize: 16,
  },
  selectedCoverImage: {
    width: normalize(358),
    height: normalize(218),
    borderWidth: 1,
    borderRadius: 5,
    borderColor: 'white',
  },
  touchableImagePickerStyle: {
    position: 'absolute',
    top: normalize(190),
    left: normalize(40),
  },
  customTextView: {
    marginLeft: normalize(15),
    marginRight: normalize(15),
  },
  SubmitButtonStyle: {
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
    color: 'black',
    marginBottom: normalize(25),
    top: normalize(10),
    fontStyle: 'italic',
  },
  SubmitButtonTouchable: {
    backgroundColor: '#44C2E3',
    width: '93%',
    alignItems: 'center',
    borderRadius: 5,
    borderWidth: 1,
    marginHorizontal: normalize(15),
  },
  ModalViewStyle: {
    marginTop: normalize(2),
    marginBottom: normalize(10),
  },
  touchableCalendarStyle: {
    height: normalize(50),
    width: '100%',
    marginTop: normalize(5),
    justifyContent: 'center',
    position: 'absolute',
    alignItems: 'flex-end',
    paddingRight: normalize(19),
    paddingTop: normalize(17),
  },
  identityView: {
    height: normalize(48),
    width: normalize(328),
    borderWidth: 1,
    borderRadius: normalize(5),
    marginVertical: normalize(10),
    borderColor: 'white',
    padding: normalize(15),
    alignSelf: 'center',
  },
  identityTxt: {
    color: 'white',
    fontSize: 14,
  },
});
